"""
Prompts模块 - 系统提示词统一管理
"""

from .system_prompts import (
    # 核心Prompt
    TASK_PLANNER_SYSTEM_PROMPT,
    TOOL_USAGE_GUIDELINES,
    RESULT_INTEGRATION_SYSTEM_PROMPT,
    CHAT_RESPONSE_SYSTEM_PROMPT,
    TOOL_NEED_CHECK_PROMPT,
    DEEP_THINKING_SYSTEM_PROMPT,
    WEB_SEARCH_RESULT_FORMAT_PROMPT,
    MAP_RESULT_FORMAT_PROMPT,
    ICL_FEW_SHOT_EXAMPLES,
    
    # 辅助函数
    get_prompt,
    get_icl_examples
)

__all__ = [
    "TASK_PLANNER_SYSTEM_PROMPT",
    "TOOL_USAGE_GUIDELINES",
    "RESULT_INTEGRATION_SYSTEM_PROMPT",
    "CHAT_RESPONSE_SYSTEM_PROMPT",
    "TOOL_NEED_CHECK_PROMPT",
    "DEEP_THINKING_SYSTEM_PROMPT",
    "WEB_SEARCH_RESULT_FORMAT_PROMPT",
    "MAP_RESULT_FORMAT_PROMPT",
    "ICL_FEW_SHOT_EXAMPLES",
    "get_prompt",
    "get_icl_examples"
]
